{'res': {'input_path': None,
         'page_index': None, 
         'model_settings': {'use_doc_preprocessor': True,
                            'use_textline_orientation': False}, 
         'doc_preprocessor_res': {'input_path': None, 
                                  'page_index': None, 
                                  'model_settings': {'use_doc_orientation_classify': False, 
                                                     'use_doc_unwarping': False}, 
                                                     'angle': -1}, 
         'dt_polys': array([[[43, 29],
        ...,
        [43, 53]]], 
        shape=(1, 4, 2), 
        dtype=int16), 
        'text_det_params': {'limit_side_len': 64, 
                            'limit_type': 'min', 
                            'thresh': 0.3, 
                            'max_side_limit': 4000, 
                            'box_thresh': 0.6, 
                            'unclip_ratio': 1.5}, 
        'text_type': 'general', 
        'textline_orientation_angles': array([-1]), 
        'text_rec_score_thresh': 0.0, 
        'rec_texts': ['HP19EQ0001'], 
        'rec_scores': array([0.99780589]), 
        'rec_polys': array([[[43, 29],
        ...,
        [43, 53]]], shape=(1, 4, 2), dtype=int16), 'rec_boxes': array([[43, ..., 56]], shape=(1, 4), dtype=int16)}}